import React, { useState } from "react";
import { 
  Building2, Sparkles, Target, FileText, MapPin, Scale, Trophy,
  X, CheckCircle2, Copy, Check, Download, Send, ArrowRight,
  ShieldCheck, AlertCircle, RefreshCw, Layers, ChevronRight,
  Sliders, Briefcase, Eye, Calendar, DollarSign, BookOpen
} from "lucide-react";
import { ArtistProfile } from "../types.js";

interface GalleryBridgeModalProps {
  isOpen: boolean;
  onClose: () => void;
  theme?: "dark-gold" | "light";
  profile: ArtistProfile;
  activeArtworkImage?: string | null;
  activeSeries?: any[];
  onAnalyzeGalleryTool?: (toolId: string) => Promise<any>;
}

export default function GalleryBridgeModal({
  isOpen,
  onClose,
  theme = "dark-gold",
  profile,
  activeArtworkImage,
  activeSeries = [],
  onAnalyzeGalleryTool
}: GalleryBridgeModalProps) {
  const [activeTab, setActiveTab] = useState<"match" | "dossier" | "murs" | "contrat" | "opencalls">("match");
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [loadingTool, setLoadingTool] = useState<string | null>(null);

  // Results state from live AI generation
  const [liveResults, setLiveResults] = useState<Record<string, any>>({});

  // Contract simulator parameters
  const [contractCommission, setContractCommission] = useState<number>(50);
  const [contractDuration, setContractDuration] = useState<string>("6 mois");
  const [contractGalleryName, setContractGalleryName] = useState<string>("Galerie de l'Atelier Moderne");
  const [contractCity, setContractCity] = useState<string>("Paris (75003)");

  // Open calls filter
  const [selectedCallType, setSelectedCallType] = useState<string>("all");

  const isDark = theme === "dark-gold";

  if (!isOpen) return null;

  const handleCopy = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2500);
  };

  const handleRunAi = async (toolId: string) => {
    if (!onAnalyzeGalleryTool) return;
    setLoadingTool(toolId);
    try {
      const res = await onAnalyzeGalleryTool(toolId);
      if (res && !res.error) {
        setLiveResults(prev => ({ ...prev, [toolId]: res }));
      }
    } catch (e) {
      console.error("Erreur lors de l'exécution de l'outil galerie:", e);
    } finally {
      setLoadingTool(null);
    }
  };

  // Mock initial defaults if not yet generated by AI
  const defaultMatchData = liveResults["gallery_match"] || {
    synthese_positionnement: `${profile.name || "L'artiste"} développe une écriture plastique singulière alliant sensibilité matérielle et rigueur compositionnelle, particulièrement prisée par les galeries d'art contemporain et les collectionneurs émergents.`,
    galeries_recommandees: [
      {
        nom_galerie: "Galerie Templon",
        ville: "Paris (Le Marais) & Bruxelles",
        ligne_editoriale: "Art contemporain international, dialogues de matières et narrations picturales puissantes",
        score_affinite: 94,
        pourquoi_ce_match: "Leur sélection valorise les artistes alliant virtuosité technique et réflexion conceptuelle affirmée.",
        conseil_approche: "Adresser une lettre personnalisée lors de la préparation des expositions d'automne avec un lien vers 5 œuvres clés."
      },
      {
        nom_galerie: "Ceysson & Bénétière",
        ville: "Paris, Lyon, Genève, New York",
        ligne_editoriale: "Support/Surface, peinture gestuelle, exploration des pigments et textures",
        score_affinite: 91,
        pourquoi_ce_match: "Forte sensibilité pour les artistes qui questionnent le médium pictural et la matérialité de la toile.",
        conseil_approche: "Mettre en avant la démarche d'atelier, les techniques de superposition et la série complète."
      },
      {
        nom_galerie: "Almine Rech Gallery",
        ville: "Paris (Matignon), Londres, New York",
        ligne_editoriale: "Avant-garde contemporaine, abstraction poétique et figuration libre",
        score_affinite: 88,
        pourquoi_ce_match: "La touche vibratoire et les harmonies de couleurs répondent aux tendances recherchées par leurs curateurs.",
        conseil_approche: "Proposer une visite privée d'atelier lors des week-ends de vernissages parisiens."
      }
    ],
    lettre_contact: `Objet : Présentation du travail d'atelier de ${profile.name || "[Votre Nom]"} — Proposition de dialogue curatorial\n\nMadame, Monsieur la Direction,\n\nJe suis avec une grande attention la programmation exigeante de votre galerie, dont l'engagement pour l'art pictural contemporain résonne profondément avec ma pratique d'atelier.\n\nMon travail s'articule autour de ${profile.style || "l'abstraction et la vibration chromatique"}, explorant la mémoire visuelle et l'énergie des matières. Je me permets de vous transmettre mon dossier de candidature comprenant une sélection resserrée de mes dernières pièces.\n\nSeriez-vous ouvert(e) à un échange ou à une visite d'atelier lors de votre prochain passage ?\n\nBien artistiquement,\n\n${profile.name || "[Votre Nom]"}\n${profile.instagram ? "Instagram : " + profile.instagram : ""}\n${profile.web ? "Portfolio : " + profile.web : ""}`
  };

  const defaultDossierData = liveResults["gallery_portfolio"] || {
    titre_dossier: `DOSSIER CURATORIAL D'ARTISTE — ${profile.name ? profile.name.toUpperCase() : "PORTFOLIO D'ATELIER"}`,
    statement_curateur: `${profile.name || "L'artiste"} explore les tensions entre forme et impulsion. Chaque toile devient le lieu d'une rencontre physique avec la matière, où le geste capte l'indicible pour l'offrir au regard du spectateur dans un équilibre souverain.`,
    biographie_pro: `${profile.name || "L'artiste"} vit et travaille en France. Diplômé(e) d'une formation artistique solide, ses œuvres ont fait l'objet d'acquisitions auprès de collectionneurs privés en Europe et font dialoguer tradition du geste pictural et abstraction contemporaine.`,
    grille_oeuvres_selectionnees: [
      { numero: "Œuvre 01", titre: "Résonance Première", dimension_conseillee: "120 x 100 cm", estimation_galerie: "2 200 € - 2 800 €", interet_curatorial: "Pièce maîtresse incarnant la rupture formelle et l'harmonie chromatique principale." },
      { numero: "Œuvre 02", titre: "Nocturne en Terre d'Ombre", dimension_conseillee: "90 x 90 cm", estimation_galerie: "1 700 € - 2 100 €", interet_curatorial: "Composition intimiste révélant la subtilité du travail sur les glacis et les ombres." },
      { numero: "Œuvre 03", titre: "Élévation Céleste", dimension_conseillee: "150 x 120 cm", estimation_galerie: "3 400 € - 4 200 €", interet_curatorial: "Grand format monumental conçu pour attirer le regard depuis la vitrine de la galerie." }
    ],
    revue_presse_fictive: `« Une peinture de souffle et de silence, où chaque couche de pigment semble contenir un fragment de temps suspendu. Une voix artistique à suivre de très près. » — Revue Beaux-Arts & Regards`,
    lettre_motivation_comite: `Au comité de sélection de la galerie,\n\nPar la présente, je soumets mon dossier artistique en vue d'une future collaboration ou d'une participation à vos expositions collectives. Ma démarche s'inscrit dans une recherche continue de maturité plastique.\n\nJe reste à votre entière disposition pour vous présenter les œuvres originales.`
  };

  const defaultMursData = liveResults["gallery_murs"] || {
    introduction_projet: "Opportunités sélectionnées pour exposer vos toiles dans des lieux vivants, sans intermédiaire contraignant, pour rencontrer directement votre public et vos premiers acheteurs.",
    types_espaces_cibles: [
      {
        type_lieu: "Pop-up Gallery éphémère (Le Marais / Saint-Germain)",
        surface_ideale: "20 à 35 mètres linéaires de cimaises blanches",
        modele_economique: "Location mutualisée (300 € / semaine à plusieurs artistes)",
        avantage_cle: "Flux piétonnier ultra qualifié de passionnés d'art et touristes collectionneurs."
      },
      {
        type_lieu: "Hôtel Boutique 4★ & 5★ (Lobby & Salons)",
        surface_ideale: "5 à 8 toiles grands formats en majesté",
        modele_economique: "Gratuit en échange d'une commission de 20% sur les ventes aux clients de l'hôtel",
        avantage_cle: "Clientèle internationale aisée en recherche d'œuvres originales pour décorer leurs résidences."
      },
      {
        type_lieu: "Tiers-Lieu Culturel & Espace Coworking d'Architectes",
        surface_ideale: "Murs bruts, éclairage sur rails orientables",
        modele_economique: "Dépôt gratuit pendant 2 mois avec vernissage d'ouverture",
        avantage_cle: "Prescripteurs directs (architectes d'intérieur, designers) toujours en quête d'art pour leurs chantiers."
      }
    ],
    pitch_candidature_espace: `Bonjour,\n\nJe suis l'artiste ${profile.name || "peintre"}, et je souhaiterais vous proposer un projet d'exposition éphémère pour habiller élégamment vos espaces avec une série de toiles contemporaines.\n\nMes créations apporteront une touche esthétique haut de gamme à votre lieu tout en valorisant vos murs auprès de vos visiteurs. Nous pourrions organiser un vernissage privé convivial d'inauguration.\n\nSeriez-vous disponible pour un court échange téléphonique ?`,
    conseils_installation: "Prévoyez des crochets cimaises réglables et des cartels adhésifs propres avec QR code renvoyant vers votre certificat COA et tarif."
  };

  const defaultOpencallsData = liveResults["gallery_opencalls"] || {
    diagnostic_candidature: `Votre univers plastique correspond aux critères d'exigence des jurys de salons parisiens et biennales régionales. Un dossier soigné avec de bonnes photos garantit un taux d'acceptation supérieur à 85%.`,
    opportunites_selectionnees: [
      {
        nom_evenement: "Salon d'Automne de Paris (Grande Halle de la Villette)",
        type_evenement: "Salon Historique International",
        score_pertinence: 95,
        interet_carriere: "Reconnaissance institutionnelle majeure, plus de 30 000 visiteurs et présence de nombreux collectionneurs.",
        strategie_jury: "Soumettre une œuvre percutante d'au moins 100x80 cm dans la section Peinture Contemporaine avec cartel explicatif."
      },
      {
        nom_evenement: "Art Capital — Salon des Artistes Français (Grand Palais)",
        type_evenement: "Foire sous la verrière du Grand Palais",
        score_pertinence: 92,
        interet_carriere: "Tremplin prestigieux sous le dôme du Grand Palais, attribution de médailles et prix de fondations.",
        strategie_jury: "Mettre en avant la maîtrise technique et la texture unique du support."
      },
      {
        nom_evenement: "Résidence de Création & Bourse d'Atelier (Fondation Taylor)",
        type_evenement: "Bourse & Résidence d'Artistes",
        score_pertinence: 89,
        interet_carriere: "Financement d'atelier, dotation financière et exposition personnelle de fin de résidence.",
        strategie_jury: "Rédiger une note d'intention claire sur l'évolution de votre démarche lors des 12 prochains mois."
      },
      {
        nom_evenement: "Biennale de la Jeune Création Européenne",
        type_evenement: "Biennale Internationale Itinérante",
        score_pertinence: 86,
        interet_carriere: "Tournée européenne de l'exposition dans 7 pays (France, Italie, Espagne, Portugal...).",
        strategie_jury: "Proposer un diptyque ou un triptyque démontrant la cohérence sérielle."
      }
    ],
    plan_action_calendrier: "T1 (Jan-Mars) : Préparation des photos HD et textes. T2 (Avril-Juin) : Soumission aux comités. T3-T4 : Sélection, vernissages et cérémonies de remise de prix."
  };

  // Generate dynamic contract text
  const generateContractText = () => {
    const artistSplit = 100 - contractCommission;
    return `CONVENTION DE DÉPÔT-VENTE D'ŒUVRES D'ART EN GALERIE

ENTRE LES SOUSSIGNÉS :
1. L'ARTISTE :
   Nom / Pseudonyme : ${profile.name || "_______________________________"}
   Demeurant à : __________________________________________________
   Email : ${profile.contactEmail || "_______________________________"}
   SIRET / Numéro Maison des Artistes : _____________________________
   (Ci-après désigné « L'Artiste »)

ET
2. LA GALERIE :
   Raison Sociale : ${contractGalleryName}
   Siège Social : ${contractCity}
   Représentée par son Directeur / Gérant
   (Ci-après désignée « La Galerie »)

IL A ÉTÉ CONVENU ET ARRÊTÉ CE QUI SUIT :

ARTICLE 1 — OBJET DU DÉPÔT
L'Artiste confie à La Galerie, qui accepte, le dépôt exclusif aux fins d'exposition et de vente des œuvres désignées en Annexe 1. L'Artiste conserve la pleine propriété intellectuelle et morale des œuvres jusqu'au paiement intégral par l'acquéreur.

ARTICLE 2 — DURÉE DU CONTRAT
La présente convention est conclue pour une durée déterminée de ${contractDuration} à compter de la date de signature. Elle pourra être renouvelée par tacite reconduction par périodes de même durée, sauf dénonciation avec préavis d'un mois.

ARTICLE 3 — PRIX DE VENTE ET COMMISSION
- Les prix de vente publics sont fixés d'un commun accord entre les parties.
- En cas de vente, La Galerie percevra une commission de ${contractCommission}% sur le prix de vente public Hors Taxes.
- L'Artiste percevra la part restante soit ${artistSplit}% du montant de la vente.
- Aucun rabais supérieur à 10% ne pourra être consenti à un acheteur sans l'accord écrit préalable de L'Artiste.

ARTICLE 4 — ASSURANCE ET RESPONSABILITÉ (« CLOU À CLOU »)
La Galerie s'engage à assurer les œuvres confiées contre le vol, l'incendie, les dégâts des eaux et les dégradations accidentelles, pour leur valeur de dépôt convenue, selon le principe de la garantie « Clou à Clou » (depuis la prise en charge jusqu'à la restitution ou la livraison).

ARTICLE 5 — RÈGLEMENT DES VENTES
La Galerie s'engage à informer L'Artiste de toute vente dans un délai maximal de huit (8) jours ouvrés, et à lui reverser les sommes dues dans un délai de trente (30) jours suivant l'encaissement effectif du paiement de l'acheteur.

ARTICLE 6 — RESTITUTION DES ŒUVRES INVENDUES
À l'échéance du présent contrat, les œuvres invendues seront restituées à L'Artiste en parfait état de conservation dans les locaux de la Galerie.

Fait à ${contractCity.split(' ')[0] || "Paris"}, le ${new Date().toLocaleDateString('fr-FR')}, en deux exemplaires originaux.

Pour l'Artiste :                                Pour la Galerie :
(Signature précédée de « Bon pour accord »)     (Signature et cachet)`;
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-2 sm:p-4 md:p-6 bg-black/80 backdrop-blur-sm animate-fadeIn">
      <div className={`w-full max-w-5xl max-h-[92vh] flex flex-col border shadow-2xl overflow-hidden transition-all ${
        isDark ? "bg-[#0d0d0d] border-[#c9a84c] text-white" : "bg-white border-[#c9a84c] text-black"
      }`}>
        
        {/* Modal Header */}
        <div className={`p-4 sm:p-5 flex items-center justify-between border-b ${
          isDark ? "bg-[#141414] border-[#c9a84c]/30" : "bg-amber-50/70 border-[#c9a84c]/30"
        }`}>
          <div className="flex items-center gap-3">
            <div className={`w-10 h-10 flex items-center justify-center border ${
              isDark ? "bg-[#c9a84c]/20 border-[#c9a84c] text-[#c9a84c]" : "bg-amber-200 border-[#c9a84c] text-[#9c7d2b]"
            }`}>
              <Building2 className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className={`font-serif text-base sm:text-lg font-bold tracking-tight ${
                  isDark ? "text-white" : "text-black"
                }`}>
                  Passerelle Galeries & Prospection Artistique
                </h2>
                <span className="text-[9px] font-mono font-black px-2 py-0.5 uppercase bg-[#c9a84c] text-black">
                  5 Outils Stratégiques
                </span>
              </div>
              <p className={`text-xs font-sans mt-0.5 font-medium ${
                isDark ? "text-neutral-300" : "text-stone-700"
              }`}>
                Matchmaking curatorial, candidatures pro, bourse aux murs libres, contrats de dépôt et salons d'art.
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className={`p-2 border transition-colors ${
              isDark 
                ? "bg-black border-white/20 text-neutral-300 hover:text-white hover:border-[#c9a84c]" 
                : "bg-white border-stone-300 text-stone-700 hover:text-black hover:border-black"
            }`}
            title="Fermer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Top 5 Tabs Navigation */}
        <div className={`flex border-b overflow-x-auto scrollbar-thin ${
          isDark ? "bg-black border-[#c9a84c]/20" : "bg-stone-100 border-stone-300"
        }`}>
          <button
            onClick={() => setActiveTab("match")}
            className={`px-4 py-3 text-xs font-mono font-bold uppercase tracking-wider flex items-center gap-2 whitespace-nowrap border-b-2 transition-all ${
              activeTab === "match"
                ? "border-[#c9a84c] text-[#c9a84c] bg-[#c9a84c]/10"
                : isDark ? "border-transparent text-neutral-400 hover:text-white" : "border-transparent text-stone-600 hover:text-black"
            }`}
          >
            <Target className="w-4 h-4" />
            1. Curator Matchmaking
          </button>

          <button
            onClick={() => setActiveTab("dossier")}
            className={`px-4 py-3 text-xs font-mono font-bold uppercase tracking-wider flex items-center gap-2 whitespace-nowrap border-b-2 transition-all ${
              activeTab === "dossier"
                ? "border-[#c9a84c] text-[#c9a84c] bg-[#c9a84c]/10"
                : isDark ? "border-transparent text-neutral-400 hover:text-white" : "border-transparent text-stone-600 hover:text-black"
            }`}
          >
            <Briefcase className="w-4 h-4" />
            2. Dossier de Candidature Pro
          </button>

          <button
            onClick={() => setActiveTab("murs")}
            className={`px-4 py-3 text-xs font-mono font-bold uppercase tracking-wider flex items-center gap-2 whitespace-nowrap border-b-2 transition-all ${
              activeTab === "murs"
                ? "border-[#c9a84c] text-[#c9a84c] bg-[#c9a84c]/10"
                : isDark ? "border-transparent text-neutral-400 hover:text-white" : "border-transparent text-stone-600 hover:text-black"
            }`}
          >
            <MapPin className="w-4 h-4" />
            3. Bourse aux Murs & Pop-up
          </button>

          <button
            onClick={() => setActiveTab("contrat")}
            className={`px-4 py-3 text-xs font-mono font-bold uppercase tracking-wider flex items-center gap-2 whitespace-nowrap border-b-2 transition-all ${
              activeTab === "contrat"
                ? "border-[#c9a84c] text-[#c9a84c] bg-[#c9a84c]/10"
                : isDark ? "border-transparent text-neutral-400 hover:text-white" : "border-transparent text-stone-600 hover:text-black"
            }`}
          >
            <Scale className="w-4 h-4" />
            4. Simulateur de Contrat Dépôt
          </button>

          <button
            onClick={() => setActiveTab("opencalls")}
            className={`px-4 py-3 text-xs font-mono font-bold uppercase tracking-wider flex items-center gap-2 whitespace-nowrap border-b-2 transition-all ${
              activeTab === "opencalls"
                ? "border-[#c9a84c] text-[#c9a84c] bg-[#c9a84c]/10"
                : isDark ? "border-transparent text-neutral-400 hover:text-white" : "border-transparent text-stone-600 hover:text-black"
            }`}
          >
            <Trophy className="w-4 h-4" />
            5. Appels à Projets & Salons
          </button>
        </div>

        {/* Tab Contents */}
        <div className="p-4 sm:p-6 overflow-y-auto flex-1 space-y-6">

          {/* TAB 1: CURATOR MATCHMAKING */}
          {activeTab === "match" && (
            <div className="space-y-6 animate-fadeIn">
              
              {/* Header Action Banner */}
              <div className={`p-4 border flex flex-col sm:flex-row sm:items-center justify-between gap-4 ${
                isDark ? "bg-[#141414] border-[#c9a84c]/40" : "bg-amber-50 border-[#c9a84c]"
              }`}>
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] font-mono font-black uppercase px-2 py-0.5 bg-[#c9a84c] text-black">
                      IA Matchmaking Artiste ↔ Galeries
                    </span>
                    <span className={`text-xs font-serif font-bold ${isDark ? "text-white" : "text-black"}`}>
                      Affinités Stylistiques & Stratégies d'Approche
                    </span>
                  </div>
                  <p className={`text-xs font-sans mt-1 ${isDark ? "text-neutral-300" : "text-stone-800"}`}>
                    {defaultMatchData.synthese_positionnement}
                  </p>
                </div>

                {onAnalyzeGalleryTool && (
                  <button
                    onClick={() => handleRunAi("gallery_match")}
                    disabled={loadingTool === "gallery_match"}
                    className="px-4 py-2 bg-[#c9a84c] hover:bg-white text-black font-mono font-black text-xs uppercase tracking-wider flex items-center gap-2 transition-colors whitespace-nowrap shadow-md"
                  >
                    <RefreshCw className={`w-3.5 h-3.5 ${loadingTool === "gallery_match" ? "animate-spin" : ""}`} />
                    {loadingTool === "gallery_match" ? "Calcul en cours..." : "Recalculer pour mes œuvres"}
                  </button>
                )}
              </div>

              {/* Matchmaking Cards Grid */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {defaultMatchData.galeries_recommandees.map((gal: any, idx: number) => (
                  <div key={idx} className={`p-4 border flex flex-col justify-between ${
                    isDark ? "bg-black border-[#c9a84c]/40 text-white" : "bg-white border-[#c9a84c] text-black shadow-md"
                  }`}>
                    <div className="space-y-2.5">
                      <div className="flex items-start justify-between gap-2 border-b pb-2 border-[#c9a84c]/20">
                        <div>
                          <h4 className="font-serif font-bold text-sm tracking-tight text-[#c9a84c]">
                            {gal.nom_galerie}
                          </h4>
                          <p className={`text-[10px] font-mono flex items-center gap-1 mt-0.5 ${isDark ? "text-neutral-300" : "text-stone-700"}`}>
                            <MapPin className="w-3 h-3 text-[#c9a84c]" />
                            {gal.ville}
                          </p>
                        </div>
                        <div className="text-right">
                          <span className="text-sm font-mono font-black text-emerald-400 bg-emerald-950/40 px-2 py-0.5 border border-emerald-500/40">
                            {gal.score_affinite}% Match
                          </span>
                        </div>
                      </div>

                      <p className="text-xs font-sans leading-relaxed">
                        <strong>Ligne éditoriale :</strong> {gal.ligne_editoriale}
                      </p>

                      <p className="text-xs font-sans leading-relaxed">
                        <strong className="text-[#c9a84c]">Pourquoi ce match :</strong> {gal.pourquoi_ce_match}
                      </p>
                    </div>

                    <div className={`mt-4 pt-3 border-t text-[11px] font-sans ${isDark ? "border-white/10" : "border-stone-200"}`}>
                      <p className="italic">
                        💡 <strong>Conseil d'approche :</strong> {gal.conseil_approche}
                      </p>
                    </div>
                  </div>
                ))}
              </div>

              {/* Pitch Email Generator Box */}
              <div className={`p-4 sm:p-5 border ${
                isDark ? "bg-[#111111] border-[#c9a84c]/40" : "bg-white border-[#c9a84c] shadow-sm"
              }`}>
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center gap-2">
                    <Send className="w-4 h-4 text-[#c9a84c]" />
                    <h4 className="text-xs font-mono font-bold uppercase tracking-wider text-[#c9a84c]">
                      Modèle d'Email de Contact pour Directeur de Galerie
                    </h4>
                  </div>

                  <button
                    onClick={() => handleCopy(defaultMatchData.lettre_contact, "pitch_email")}
                    className={`px-3 py-1.5 text-xs font-mono font-bold uppercase tracking-wider flex items-center gap-1.5 border transition-all ${
                      copiedKey === "pitch_email"
                        ? "bg-emerald-600 text-white border-emerald-500"
                        : (isDark ? "bg-black text-[#c9a84c] border-[#c9a84c] hover:bg-[#c9a84c] hover:text-black" : "bg-stone-100 text-stone-900 border-stone-300 hover:bg-stone-200")
                    }`}
                  >
                    {copiedKey === "pitch_email" ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                    {copiedKey === "pitch_email" ? "Copié !" : "Copier le texte"}
                  </button>
                </div>

                <pre className={`p-4 border text-xs font-mono whitespace-pre-wrap leading-relaxed overflow-x-auto ${
                  isDark ? "bg-black border-white/10 text-neutral-200" : "bg-stone-50 border-stone-200 text-stone-900"
                }`}>
                  {defaultMatchData.lettre_contact}
                </pre>
              </div>

            </div>
          )}

          {/* TAB 2: DOSSIER DE CANDIDATURE PRO */}
          {activeTab === "dossier" && (
            <div className="space-y-6 animate-fadeIn">
              <div className={`p-4 border flex flex-col sm:flex-row sm:items-center justify-between gap-4 ${
                isDark ? "bg-[#141414] border-[#c9a84c]/40" : "bg-amber-50 border-[#c9a84c]"
              }`}>
                <div>
                  <h3 className="font-serif font-bold text-sm sm:text-base text-[#c9a84c]">
                    {defaultDossierData.titre_dossier}
                  </h3>
                  <p className={`text-xs font-sans mt-0.5 ${isDark ? "text-neutral-300" : "text-stone-800"}`}>
                    Format standardisé prêt à soumettre aux comités de sélection, foires et directeurs artistiques.
                  </p>
                </div>

                <div className="flex gap-2">
                  {onAnalyzeGalleryTool && (
                    <button
                      onClick={() => handleRunAi("gallery_portfolio")}
                      disabled={loadingTool === "gallery_portfolio"}
                      className="px-3 py-1.5 bg-[#c9a84c] hover:bg-white text-black font-mono font-black text-xs uppercase tracking-wider flex items-center gap-1.5 transition-colors"
                    >
                      <RefreshCw className={`w-3 h-3 ${loadingTool === "gallery_portfolio" ? "animate-spin" : ""}`} />
                      Actualiser
                    </button>
                  )}
                  <button
                    onClick={() => handleCopy(
                      `${defaultDossierData.titre_dossier}\n\n=== STATEMENT CURATORIAL ===\n${defaultDossierData.statement_curateur}\n\n=== BIOGRAPHIE ===\n${defaultDossierData.biographie_pro}\n\n=== SÉLECTION D'ŒUVRES ===\n` +
                      defaultDossierData.grille_oeuvres_selectionnees.map((o: any) => `${o.numero} : ${o.titre} (${o.dimension_conseillee}) — Prix suggéré: ${o.estimation_galerie}\nIntérêt: ${o.interet_curatorial}`).join("\n\n") +
                      `\n\n=== REVUE DE PRESSE ===\n${defaultDossierData.revue_presse_fictive}\n\n=== LETTRE AU COMITÉ ===\n${defaultDossierData.lettre_motivation_comite}`,
                      "dossier_full"
                    )}
                    className="px-3 py-1.5 bg-black border border-[#c9a84c] text-[#c9a84c] hover:bg-[#c9a84c] hover:text-black font-mono font-bold text-xs uppercase tracking-wider flex items-center gap-1.5 transition-colors"
                  >
                    {copiedKey === "dossier_full" ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                    {copiedKey === "dossier_full" ? "Dossier Copié !" : "Copier le Dossier Complet"}
                  </button>
                </div>
              </div>

              {/* Curatorial Statement & Bio */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className={`p-4 border ${isDark ? "bg-black border-[#c9a84c]/40" : "bg-white border-[#c9a84c]"}`}>
                  <h4 className="text-xs font-mono font-bold uppercase text-[#c9a84c] mb-2 flex items-center gap-2">
                    <FileText className="w-4 h-4" /> Statement Curatorial
                  </h4>
                  <p className="text-xs font-sans leading-relaxed">
                    {defaultDossierData.statement_curateur}
                  </p>
                </div>

                <div className={`p-4 border ${isDark ? "bg-black border-[#c9a84c]/40" : "bg-white border-[#c9a84c]"}`}>
                  <h4 className="text-xs font-mono font-bold uppercase text-[#c9a84c] mb-2 flex items-center gap-2">
                    <Briefcase className="w-4 h-4" /> Biographie Professionnelle
                  </h4>
                  <p className="text-xs font-sans leading-relaxed">
                    {defaultDossierData.biographie_pro}
                  </p>
                </div>
              </div>

              {/* Selected Artworks Grid Table */}
              <div className={`border p-4 ${isDark ? "bg-black border-[#c9a84c]/40" : "bg-white border-[#c9a84c]"}`}>
                <h4 className="text-xs font-mono font-bold uppercase text-[#c9a84c] mb-3 flex items-center gap-2">
                  <Layers className="w-4 h-4" /> Sélection de Pièces Maîtresses pour la Galerie
                </h4>

                <div className="space-y-3">
                  {defaultDossierData.grille_oeuvres_selectionnees.map((item: any, idx: number) => (
                    <div key={idx} className={`p-3 border flex flex-col sm:flex-row sm:items-center justify-between gap-3 ${
                      isDark ? "bg-neutral-900/60 border-white/10" : "bg-stone-50 border-stone-200"
                    }`}>
                      <div>
                        <div className="flex items-center gap-2">
                          <span className="text-[10px] font-mono font-bold px-2 py-0.5 bg-[#c9a84c] text-black uppercase">
                            {item.numero}
                          </span>
                          <strong className="text-xs font-serif text-base font-bold">{item.titre}</strong>
                          <span className="text-[11px] font-mono text-neutral-400">({item.dimension_conseillee})</span>
                        </div>
                        <p className="text-xs font-sans text-neutral-300 mt-1">
                          {item.interet_curatorial}
                        </p>
                      </div>

                      <div className="text-right flex-shrink-0">
                        <span className="text-xs font-mono font-bold text-[#c9a84c] bg-[#c9a84c]/10 px-2.5 py-1 border border-[#c9a84c]/30">
                          {item.estimation_galerie}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Press review & Cover letter */}
              <div className={`p-4 border ${isDark ? "bg-[#141414] border-[#c9a84c]/30" : "bg-stone-50 border-stone-200"}`}>
                <p className="text-xs italic text-[#c9a84c] font-serif mb-3">
                  {defaultDossierData.revue_presse_fictive}
                </p>
                <div className="text-xs font-mono leading-relaxed whitespace-pre-wrap pt-3 border-t border-white/10">
                  <strong>Lettre d'accompagnement au comité :</strong>
                  <p className="mt-1">{defaultDossierData.lettre_motivation_comite}</p>
                </div>
              </div>

            </div>
          )}

          {/* TAB 3: BOURSE AUX MURS & POP-UP */}
          {activeTab === "murs" && (
            <div className="space-y-6 animate-fadeIn">
              <div className={`p-4 border flex flex-col sm:flex-row sm:items-center justify-between gap-4 ${
                isDark ? "bg-[#141414] border-[#c9a84c]/40" : "bg-amber-50 border-[#c9a84c]"
              }`}>
                <div>
                  <h3 className="font-serif font-bold text-sm sm:text-base text-[#c9a84c]">
                    Bourse aux Murs Libres & Espaces d'Exposition Partagés
                  </h3>
                  <p className={`text-xs font-sans mt-0.5 ${isDark ? "text-neutral-300" : "text-stone-800"}`}>
                    {defaultMursData.introduction_projet}
                  </p>
                </div>

                {onAnalyzeGalleryTool && (
                  <button
                    onClick={() => handleRunAi("gallery_murs")}
                    disabled={loadingTool === "gallery_murs"}
                    className="px-4 py-2 bg-[#c9a84c] hover:bg-white text-black font-mono font-black text-xs uppercase tracking-wider flex items-center gap-2 transition-colors whitespace-nowrap"
                  >
                    <RefreshCw className={`w-3.5 h-3.5 ${loadingTool === "gallery_murs" ? "animate-spin" : ""}`} />
                    Trouver d'autres lieux
                  </button>
                )}
              </div>

              {/* Spaces Cards */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {defaultMursData.types_espaces_cibles.map((esp: any, idx: number) => (
                  <div key={idx} className={`p-4 border flex flex-col justify-between ${
                    isDark ? "bg-black border-[#c9a84c]/40" : "bg-white border-[#c9a84c] shadow-md"
                  }`}>
                    <div className="space-y-2.5">
                      <div className="flex items-center gap-2 border-b pb-2 border-[#c9a84c]/20">
                        <MapPin className="w-4 h-4 text-[#c9a84c]" />
                        <h4 className="font-serif font-bold text-xs text-[#c9a84c]">
                          {esp.type_lieu}
                        </h4>
                      </div>

                      <p className="text-xs font-sans">
                        <strong>Cimaises :</strong> {esp.surface_ideale}
                      </p>

                      <p className="text-xs font-sans">
                        <strong>Modèle :</strong> {esp.modele_economique}
                      </p>

                      <p className="text-xs font-sans text-neutral-300">
                        <strong>Avantage :</strong> {esp.avantage_cle}
                      </p>
                    </div>

                    <div className="mt-4 pt-3 border-t border-white/10">
                      <button
                        onClick={() => handleCopy(defaultMursData.pitch_candidature_espace, `pitch_mur_${idx}`)}
                        className="w-full py-1.5 bg-[#c9a84c]/20 text-[#c9a84c] hover:bg-[#c9a84c] hover:text-black border border-[#c9a84c]/50 text-[10px] font-mono font-bold uppercase tracking-wider transition-colors"
                      >
                        {copiedKey === `pitch_mur_${idx}` ? "Pitch Copié !" : "Copier le Pitch Lieu"}
                      </button>
                    </div>
                  </div>
                ))}
              </div>

              {/* Pitch Model & Installation advice */}
              <div className={`p-4 border ${isDark ? "bg-black border-[#c9a84c]/40" : "bg-white border-[#c9a84c]"}`}>
                <h4 className="text-xs font-mono font-bold uppercase text-[#c9a84c] mb-2">
                  Proposition Type à Envoyer aux Gestionnaires d'Espaces & Hôtels
                </h4>
                <pre className={`p-3 border text-xs font-mono whitespace-pre-wrap leading-relaxed mb-3 ${
                  isDark ? "bg-neutral-900 border-white/10 text-neutral-200" : "bg-stone-50 border-stone-200 text-stone-900"
                }`}>
                  {defaultMursData.pitch_candidature_espace}
                </pre>
                <p className="text-xs italic text-[#c9a84c]">
                  📌 {defaultMursData.conseils_installation}
                </p>
              </div>
            </div>
          )}

          {/* TAB 4: SIMULATEUR DE CONTRAT DE DÉPÔT-VENTE */}
          {activeTab === "contrat" && (
            <div className="space-y-6 animate-fadeIn">
              
              {/* Parameter controls */}
              <div className={`p-4 border ${isDark ? "bg-[#141414] border-[#c9a84c]" : "bg-amber-50 border-[#c9a84c]"}`}>
                <div className="flex items-center gap-2 mb-3">
                  <Sliders className="w-4 h-4 text-[#c9a84c]" />
                  <h3 className="font-serif font-bold text-sm text-[#c9a84c]">
                    Paramètres de la Convention de Dépôt-Vente
                  </h3>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-4 gap-3 text-xs font-sans">
                  <div>
                    <label className="block text-[10px] font-mono uppercase text-neutral-400 mb-1">
                      Part Galerie / Artiste
                    </label>
                    <select
                      value={contractCommission}
                      onChange={(e) => setContractCommission(Number(e.target.value))}
                      className={`w-full p-2 border font-mono text-xs font-bold ${
                        isDark ? "bg-black border-[#c9a84c] text-white" : "bg-white border-stone-300 text-black"
                      }`}
                    >
                      <option value={50}>50% Galerie / 50% Artiste (Standard)</option>
                      <option value={40}>40% Galerie / 60% Artiste (Avantageux)</option>
                      <option value={30}>30% Galerie / 70% Artiste (Dépôt simple)</option>
                      <option value={60}>60% Galerie / 40% Artiste (Prestige)</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-[10px] font-mono uppercase text-neutral-400 mb-1">
                      Durée du Dépôt
                    </label>
                    <select
                      value={contractDuration}
                      onChange={(e) => setContractDuration(e.target.value)}
                      className={`w-full p-2 border font-mono text-xs font-bold ${
                        isDark ? "bg-black border-[#c9a84c] text-white" : "bg-white border-stone-300 text-black"
                      }`}
                    >
                      <option value="1 mois">1 mois (Événementiel)</option>
                      <option value="3 mois">3 mois (Saison d'exposition)</option>
                      <option value="6 mois">6 mois (Standard)</option>
                      <option value="1 an">1 an (Représentation longue)</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-[10px] font-mono uppercase text-neutral-400 mb-1">
                      Nom de la Galerie
                    </label>
                    <input
                      type="text"
                      value={contractGalleryName}
                      onChange={(e) => setContractGalleryName(e.target.value)}
                      className={`w-full p-2 border text-xs ${
                        isDark ? "bg-black border-white/20 text-white" : "bg-white border-stone-300 text-black"
                      }`}
                    />
                  </div>

                  <div>
                    <label className="block text-[10px] font-mono uppercase text-neutral-400 mb-1">
                      Ville & Juridiction
                    </label>
                    <input
                      type="text"
                      value={contractCity}
                      onChange={(e) => setContractCity(e.target.value)}
                      className={`w-full p-2 border text-xs ${
                        isDark ? "bg-black border-white/20 text-white" : "bg-white border-stone-300 text-black"
                      }`}
                    />
                  </div>
                </div>
              </div>

              {/* Full Legal Contract Preview Box */}
              <div className={`p-4 border ${isDark ? "bg-black border-[#c9a84c]" : "bg-white border-[#c9a84c] shadow-lg"}`}>
                <div className="flex items-center justify-between mb-3 border-b pb-2 border-[#c9a84c]/20">
                  <div className="flex items-center gap-2">
                    <ShieldCheck className="w-4 h-4 text-[#c9a84c]" />
                    <h4 className="text-xs font-mono font-bold uppercase tracking-wider text-[#c9a84c]">
                      Texte Officiel du Contrat (Prêt à Signer & Imprimer)
                    </h4>
                  </div>

                  <div className="flex gap-2">
                    <button
                      onClick={() => handleCopy(generateContractText(), "contract_full")}
                      className="px-3 py-1.5 bg-[#c9a84c] text-black hover:bg-white text-xs font-mono font-black uppercase tracking-wider flex items-center gap-1.5 transition-colors"
                    >
                      {copiedKey === "contract_full" ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                      {copiedKey === "contract_full" ? "Contrat Copié !" : "Copier le Contrat"}
                    </button>
                  </div>
                </div>

                <pre className={`p-4 border text-[11px] font-mono leading-relaxed whitespace-pre-wrap max-h-80 overflow-y-auto ${
                  isDark ? "bg-neutral-900 border-white/10 text-neutral-200" : "bg-stone-50 border-stone-200 text-stone-900"
                }`}>
                  {generateContractText()}
                </pre>
              </div>

              {/* 4 Points of Vigilance */}
              <div className={`p-4 border ${isDark ? "bg-[#141414] border-white/10" : "bg-stone-50 border-stone-200"}`}>
                <h4 className="text-xs font-mono font-bold uppercase text-[#c9a84c] mb-2 flex items-center gap-2">
                  <AlertCircle className="w-4 h-4" /> 4 Points de Vigilance Indispensables Avant Signature
                </h4>
                <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs font-sans">
                  <li className="flex items-start gap-2">
                    <span className="text-[#c9a84c] font-bold">1.</span>
                    <span><strong>Assurance Clou à Clou</strong> : Exigez impérativement l'attestation d'assurance de la galerie.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-[#c9a84c] font-bold">2.</span>
                    <span><strong>Délai de Paiement</strong> : Ne dépassez jamais 30 jours après l'encaissement effectif de l'acheteur.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-[#c9a84c] font-bold">3.</span>
                    <span><strong>Exclusivité Territoriale</strong> : Limitez l'exclusivité à la ville ou au quartier de la galerie, jamais au pays entier.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-[#c9a84c] font-bold">4.</span>
                    <span><strong>Frais Annexes</strong> : Refusez les frais de vernissage ou de catalogue imposés à l'artiste.</span>
                  </li>
                </ul>
              </div>

            </div>
          )}

          {/* TAB 5: APPELS À PROJETS & SALONS D'ART */}
          {activeTab === "opencalls" && (
            <div className="space-y-6 animate-fadeIn">
              <div className={`p-4 border flex flex-col sm:flex-row sm:items-center justify-between gap-4 ${
                isDark ? "bg-[#141414] border-[#c9a84c]/40" : "bg-amber-50 border-[#c9a84c]"
              }`}>
                <div>
                  <h3 className="font-serif font-bold text-sm sm:text-base text-[#c9a84c]">
                    Grands Salons, Biennales & Prix d'Art Contemporain
                  </h3>
                  <p className={`text-xs font-sans mt-0.5 ${isDark ? "text-neutral-300" : "text-stone-800"}`}>
                    {defaultOpencallsData.diagnostic_candidature}
                  </p>
                </div>

                {onAnalyzeGalleryTool && (
                  <button
                    onClick={() => handleRunAi("gallery_opencalls")}
                    disabled={loadingTool === "gallery_opencalls"}
                    className="px-4 py-2 bg-[#c9a84c] hover:bg-white text-black font-mono font-black text-xs uppercase tracking-wider flex items-center gap-2 transition-colors whitespace-nowrap"
                  >
                    <RefreshCw className={`w-3.5 h-3.5 ${loadingTool === "gallery_opencalls" ? "animate-spin" : ""}`} />
                    Auditer mon profil
                  </button>
                )}
              </div>

              {/* Opportunities list */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {defaultOpencallsData.opportunites_selectionnees.map((call: any, idx: number) => (
                  <div key={idx} className={`p-4 border flex flex-col justify-between ${
                    isDark ? "bg-black border-[#c9a84c]/40 text-white" : "bg-white border-[#c9a84c] text-black shadow-md"
                  }`}>
                    <div className="space-y-2">
                      <div className="flex items-start justify-between gap-2 border-b pb-2 border-[#c9a84c]/20">
                        <div>
                          <span className="text-[9px] font-mono font-bold px-2 py-0.5 bg-[#c9a84c]/20 text-[#c9a84c] uppercase">
                            {call.type_evenement}
                          </span>
                          <h4 className="font-serif font-bold text-sm text-[#c9a84c] mt-1">
                            {call.nom_evenement}
                          </h4>
                        </div>
                        <span className="text-xs font-mono font-black text-emerald-400 bg-emerald-950/40 px-2 py-0.5 border border-emerald-500/40">
                          {call.score_pertinence}% Pertinence
                        </span>
                      </div>

                      <p className="text-xs font-sans leading-relaxed">
                        <strong>Impact Carrière :</strong> {call.interet_carriere}
                      </p>

                      <p className="text-xs font-sans leading-relaxed text-neutral-300">
                        <strong className="text-[#c9a84c]">Stratégie Jury :</strong> {call.strategie_jury}
                      </p>
                    </div>

                    <div className="mt-3 pt-2 border-t border-white/10 text-right">
                      <button
                        onClick={() => handleCopy(`Candidature pour ${call.nom_evenement}\nStratégie Jury : ${call.strategie_jury}\nImpact visé : ${call.interet_carriere}`, `call_${idx}`)}
                        className="text-[10px] font-mono font-bold text-[#c9a84c] hover:underline"
                      >
                        {copiedKey === `call_${idx}` ? "Stratégie copiée !" : "Copier la stratégie jury →"}
                      </button>
                    </div>
                  </div>
                ))}
              </div>

              {/* Timeline Strategy */}
              <div className={`p-4 border ${isDark ? "bg-black border-[#c9a84c]/40" : "bg-white border-[#c9a84c]"}`}>
                <h4 className="text-xs font-mono font-bold uppercase text-[#c9a84c] mb-2 flex items-center gap-2">
                  <Calendar className="w-4 h-4" /> Calendrier de Préparation Recommandé
                </h4>
                <p className="text-xs font-sans leading-relaxed">
                  {defaultOpencallsData.plan_action_calendrier}
                </p>
              </div>

            </div>
          )}

        </div>

        {/* Modal Footer */}
        <div className={`p-3.5 sm:p-4 border-t flex items-center justify-between ${
          isDark ? "bg-[#141414] border-[#c9a84c]/30 text-neutral-300" : "bg-stone-100 border-stone-200 text-stone-700"
        }`}>
          <div className="flex items-center gap-2 text-xs font-mono">
            <CheckCircle2 className="w-4 h-4 text-[#c9a84c]" />
            <span>Module 1/4 Activé — Galeries & Artistes</span>
          </div>

          <button
            onClick={onClose}
            className="px-5 py-2 bg-[#c9a84c] hover:bg-white text-black font-mono font-bold text-xs uppercase tracking-wider transition-colors shadow-md"
          >
            Fermer le Module
          </button>
        </div>

      </div>
    </div>
  );
}
